arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - r_finger_joint
    - l_finger_joint

  contriants:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.02
    r_finger_joint:
      trajectory: 0.05
      goal: 0.02
    l_finger_joint:
      trajectory: 0.05
      goal: 0.02

  gains:
    r_finger_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
    l_finger_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}    

  state_publish_rate: 25
  action_monitor_rate: 30
  stop_trajectory_duration: 0
