<?xml version="1.0" ?>
<robot name="ur5_gripper" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- start: including -->
  <!-- gripper -->
  <xacro:include filename="$(find mrk_robot_support)/urdf/gripper.xacro" />
  <!-- gazebo stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro" />
  <xacro:include filename="$(find mrk_robot_support)/urdf/gazebo_extension.xacro" />
  <!-- ur5 -->
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />
  <!-- end: including -->
  
  <!-- start: properties -->
  <xacro:property name="stand_radius" value="0.08" />
  <xacro:property name="stand_length" value="1.1" />
  <xacro:property name="stand_mass" value="20.0" />
  <xacro:property name="arm_prefix" value=""/>
  <!-- end: properties -->

  <!-- start: compentens instantiating -->
  <!-- arm instance-->
  <xacro:ur5_robot prefix="${arm_prefix}" joint_limited="true"/>

  <!-- gripper instance-->

  <!-- end: compentens instantiating -->
  
  <!-- start: xacro cylinder inertial -->
  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>
  <!-- end: xacro cylinder inertial -->
  
  <!-- start: xacro cylinder geometry -->
  <xacro:macro name="cylinder_geometry" params="radius length">
    <cylinder radius="${radius}" length="${length}"/>
  </xacro:macro>
  <!-- end: xacro cylinder geometry -->
  
  <!-- start: world link/joint -->
  <link name="world" />

  <joint name="world_to_stand" type="fixed">
    <parent link="world" />
    <child link = "stand_link" />
    <origin xyz="0.0 0.0 ${stand_length/2}" rpy="0.0 0.0 0.0" />
  </joint>  
  <!-- end: world link -->
  
  <!-- start: base link/joint -->
  <link name="stand_link">
    <visual>
      <geometry>
        <xacro:cylinder_geometry radius="${stand_radius}" length="${stand_length}" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <xacro:cylinder_geometry radius="${stand_radius}" length="${stand_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial radius="${stand_radius}" length="${stand_length}" mass="${stand_mass}">
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>

  <joint name="stand_to_robot" type="fixed">
    <parent link="stand_link" />
    <child link = "base_link" />
    <origin xyz="0.0 0.0 ${stand_length/2}" rpy="0.0 0.0 0.0" />
  </joint>  
  <!-- end: base link -->
  
  <!-- start: arm-gripper joint -->
    <joint name="${arm_prefix}to_gripper" type="fixed">
      <parent link="${arm_prefix}ee_link"/>
      <child link="gripper_ankle"/>
      <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/> 
    </joint>
  <!-- end: arm-gripper joint -->
</robot>
